name: Docker Test
on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install yaml
      run: |
          pip install pyyaml

    - name: Get latest model folder
      id: get_latest_folder
      run: |
          python ./.github/workflows/get_latest_model_name.py > latest_folder.txt

    - name: Read latest folder name
      id: read_latest_folder
      run: echo "model_folder=$(cat latest_folder.txt)" >> $GITHUB_ENV
      
    - name: Get Dockerfile path
      id: get_dockerfile_path
      run: |
          python ./.github/workflows/get_dockerfile_path.py > dockerfile_path.txt
      
    - name: Read Dockerfile path
      id: read_dockerfile_path
      run: echo "dockerfile_path=$(cat dockerfile_path.txt)" >> $GITHUB_ENV
      
    - name: Set Docker image name
      id: set_image_name
      run: |
          echo "image_name=neuronets/${{ env.model_folder }}" >> $GITHUB_ENV

    - name: Update yaml file
      id: update_yaml
      run: python ./.github/workflows/update_yaml_info.py

    - name: Generate Model Card
      id: generate_model_card
      run: |
        python ./.github/workflows/create_model_card.py

    - name: Build and push Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        cd DeepCSR/deepcsr/1.0
        docker build -t neuronets/testing_image .
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        docker push neuronets/testing_image
